config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
    get "/users/sign_in", to: "application#render_404"
  end

  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  },
  # 不要なアクションをスキップ
  skip: [ :registrations, :password ]

  root "static_pages#top"

  post "callback" => "linebot#callback"

  resources :items
  resources :notifications, only: %i[edit update]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  match "*path", to: "application#render_404", via: :all
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :user
    has_one :notification, dependent: :destroy

    validates :category, presence: true
    validates :name, presence: true, uniqueness: { scope: :user_id }, length: { maximum: 30 }
    validates :volume, presence: true, numericality: { only_integer: true, other_than: 0 }
    validates :used_count_per_weekly, presence: true, numericality: { only_integer: true, other_than: 0 }
    validates :memo, length: { maximum: 65_535 }

    scope :order_by_notification_date_asc, -> { order(Notification.arel_table[:next_notification_day].asc) }
    scope :order_by_category, -> { order(category: :desc) }
    scope :order_by_updated_at, -> { order(updated_at: :desc) }

    # 一日の平均使用量
    AVERAGE_USAGE = {
        "shampoo" => 6,
        "body_soap" => 6,
        "laundry_detergent_powder" => 20,
        "laundry_detergent_liquid" => 25,
        "fabric_softeners" => 25,
        "dishwashing_detergent" => 4,
        "lotion" => 5,
        "serum" => 3,
        "moisturising_cream" => 2,
        "face_wash" => 1,
        "sunscreen" => 2,
        "others" => 10
    }

    def calculate_next_notification_day
        return Date.today + 14.days if category == "others"

        daily_usage = calculate_daily_usage
        notification_volume = (self.volume * 1.0 / 3).ceil(2)

        days = 0
        max_days = 365
        while days < max_days
            reminding_volume = self.volume - (daily_usage * days)
            if reminding_volume <= notification_volume
                break
            else
                days += 1
            end
        end
        # 日付を返す
        Date.today + days
    end

    def calculate_interval(next_notification_day)
        (next_notification_day - Date.today).to_i
    end

    def linebot_calculate_next_notification_day
        return 14 if self.category == "others"

        daily_usage = calculate_daily_usage
        notification_volume = (self.volume * 1.0 / 3).ceil(2)
        total_volume = notification_volume + self.volume

        days = 0
        max_days = 365
        while days < max_days
            reminding_volume = total_volume - (daily_usage * days)
            if reminding_volume <= notification_volume
                break
            else
                days += 1
            end
        end
        # 日数を返す
        days
    end

    private

    def calculate_daily_usage
        average_usage = AVERAGE_USAGE[self.category] || 0
        used_count_per_weekly = self.used_count_per_weekly.to_i
        average_usage * ((used_count_per_weekly / 7.0).ceil(2))
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_item, only: [ :show, :edit, :update ]

  def index
    @items = current_user.items.joins(:notification).includes(:user, :notification)

    case params[:sort]
    when "category"
      @items = @items.order_by_category
    when "updated_at"
      @items = @items.order_by_updated_at
    when "notification_date", nil
      @items = @items.order_by_notification_date_asc
    end
  end

  def show
    @notification = @item.notification
  end

  def new
    @item = current_user.items.build
  end

  def create
    ActiveRecord::Base.transaction do
      @item = current_user.items.build(item_params)

      if @item.valid?
        next_notification_day = @item.calculate_next_notification_day
        notification_interval = @item.calculate_interval(next_notification_day)

        @notification = @item.build_notification(
          next_notification_day: next_notification_day,
          notification_interval: notification_interval
        )
        if @notification.valid?
          @item.save!
          @notification.save!
          redirect_to items_path, notice: "新たに日用品を登録しました"
        else
          render :new, status: :unprocessable_entity
        end
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit; end

  def update
    registered_volume = @item.volume
    registered_used_count_per_weekly = @item.used_count_per_weekly

    if @item.update(item_params)
      # 既存のデータと異なるかを比較
      if registered_volume != @item.volume || registered_used_count_per_weekly != @item.used_count_per_weekly
        @item.notification.item_update_next_notification_day
      end
        redirect_to items_path, notice: "登録内容を更新しました"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    item = Item.find(params[:id])
    if item.destroy
      redirect_to items_path, notice: "日用品を削除しました"
    else
      redirect_to items_path, alert: "削除に失敗しました"
    end
  end

  private

  def set_item
    @item = current_user.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:category, :name, :volume, :used_count_per_weekly, :memo)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="min-h-screen flex justify-center items-center">
    <div class="container rounded-lg w-full max-w-xl mx-auto p-8 bg-[#f8fffb]/75 shadow-lg">
        <div class="p-4">
            <div class="font-bold mt-8 text-center text-5xl text-green-800 mb-6">編集</div>
            <div data-controller="items category-icon">
                <%= render 'shared/form', form_label: '更新' %>
            </div>
        </div>
    </div>
</div>

app/views/items/index.html.erb
<div class="py-8">
  <div class="container m-8 p-8 shadow-lg max-w-4xl mx-auto bg-[#f8fffb]/75 px-4">
      <div class="font-bold mt-8 text-center text-5xl text-green-800 mb-8">登録一覧</div>
    <%= render 'shared/flash_message' %>
    <div class="font-bold text-xl">
      <div class="flex justify-between items-center m-4">
        <select class="select border px-2 py-1 w-32" onchange="location.href=this.value">
          <option disabled selected>並び替え</option>
          <option value="<%= items_path(sort: 'category') %>"<%= "selected" if params[:sort] == "category" %>>カテゴリー</option>
          <option value="<%= items_path(sort: 'updated_at') %>"<%= "selected" if params[:sort] == "updated_at" %>>更新日時</option>
          <option value="<%= items_path(sort: 'notification_date') %>"<%= "selected" if params[:sort] == "notification_date" %>>次回の通知日</option>
        </select>
        <%= link_to new_item_path, class: 'text-3xl text-blue-500 hover:text-blue-700' do %>
          <i class="fa-solid fa-square-plus text-5xl"></i>
        <% end %>
      </div>
      <% if @items.present? %>
        <ul class="space-y-5 mt-4">
          <% @items.each do |item| %>
          <!-- スマホ画面で表示 -->
            <div class="block md:hidden">
              <div class="mx-auto rounded-lg shadow-lg border overflow-hidden bg-gray-100">
                <div class="relative pb-[60%]">
                  <a href="<%= item_path(item) %>" class="flex-shrink-0 hover:shadow-2xl transition-shadow">
                  <%= image_tag "icons/#{item.category}.jpg",
                        class: "absolute object-cover h-full w-full rounded-lg border-4", 
                        alt: item.name %>
                  </a>
                </div>
                <div class="p-4 space-y-3">
                  <p class="text-xl">カテゴリー : <%= t("categories.#{item.category}") %></p>
                  <p class="text-lg">商品名 : <%= item.name %></p>
                  <div class="flex items-baseline gap-3">
                    <p class="text-xl">次回の通知日</p>
                    <p id=<%= "notification_mobile_#{item.notification.id}" %> class="text-3xl font-bold text-red-600">
                      <%= item.notification.next_notification_day %>
                    </p>
                  </div>
                  <div class="flex justify-end space-x-4 mt-3">
                    <%= link_to edit_notification_path(item), data: {turbo_frame: "modal"}, class: "text-gray-500 hover:text-gray-700" do %>
                      <i class="fas fa-clock text-2xl"></i>
                    <% end %>
                    <%= link_to edit_item_path(item), class: "text-gray-500 hover:text-gray-700" do %>
                      <i class="fas fa-pen text-2xl"></i>
                    <% end %>
                    <%= link_to item_path(item), method: :delete, data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: "text-gray-500 hover:text-gray-700" do %>
                      <i class="fas fa-trash text-2xl"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>

            <!-- PC画面で表示 -->
            <div class="hidden md:block">
              <div class="flex bg-gray-100 shadow-lg rounded-lg w-4xl">
                <a href="<%= item_path(item) %>" class="flex-shrink-0 hover:shadow-2xl transition-shadow">
                  <%= image_tag("icons/#{item.category}.jpg",
                      class: "rounded-lg w-60 border-4 border-base-200", 
                        alt: item.name) %>
                </a>
                <div class="ml-6 flex-grow relative flex flex-col justify-start items-start py-4 h-32">
                  <div class="mb-1">
                    <p class="text-xl">カテゴリー : <%= t("categories.#{item.category}") %></p>
                  </div>
                  <div class="my-2">
                    <p class="text-lg">商品名 : <%= item.name %></p>
                  </div>
                  <div class="flex flex-auto mt-1 items-baseline gap-3">
                    <p class="text-xl">次回の通知日</p>
                    <p id=<%= "notification_desktop_#{item.notification.id}" %> class="text-3xl font-bold text-red-600">
                      <%= item.notification.next_notification_day %>
                    </p>
                  </div>
                  <div class="absolute top-2 right-2">
                    <div class="space-x-5">
                      <%= link_to edit_notification_path(item), data: {turbo_frame: "modal"}, class: "text-gray-500 hover:text-gray-700" do %>
                        <i class="fas fa-clock text-3xl"></i>
                      <% end %>
                      <%= link_to edit_item_path(item), class: "text-gray-500 hover:text-gray-700" do %>
                        <i class="fas fa-pen text-3xl"></i>
                      <% end %>
                      <%= link_to item_path(item), method: :delete, data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: "text-gray-500 hover:text-gray-700" do %>
                        <i class="fas fa-trash text-3xl"></i>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </ul>
      <% else %>
        <div class="mb-3 text-center text-3xl text-gray-500">
          まず左上の <i class="fa-solid fa-square-plus text-3xl text-blue-500"></i> から登録してみましょう！
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="min-h-screen flex justify-center items-center">
  <div class="container rounded-lg w-full max-w-xl mx-auto p-8 bg-[#f8fffb]/75 shadow-lg">
    <div class="p-4">
      <div class="font-bold mt-8 text-center text-5xl text-green-800 mb-6">新規登録</div>
      <div data-controller="items category-icon">
        <%= render 'shared/form', form_label: '登録' %>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="py-8">
    <div class="container rounded-lg shadow-lg max-w-4xl mx-auto bg-[#f8fffb] px-4">
        <div class="p-2 md:p-4">
            <div class="font-bold mt-8 text-center text-5xl text-green-800 mb-6">登録内容</div>
            <div class="flex justify-end space-x-6 p-4">
                <%= link_to edit_notification_path(@item), data: {turbo_frame: "modal"}, class: "text-gray-500 hover:text-gray-700" do %>
                    <i class="fas fa-clock text-3xl"></i>
                <% end %>
                <%= link_to edit_item_path(@item), class: "text-gray-500 hover:text-gray-700" do %>
                    <i class="fas fa-pen text-3xl"></i>
                <% end %>
                <%= link_to item_path(@item), method: :delete, data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: "text-gray-500 hover:text-gray-700" do %>
                    <i class="fas fa-trash text-3xl"></i>
                <% end %>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-2 gap-8 justify-center rounded-lg">
                <div class="mb-4">
                    <div class="bg-gray-100 p-4 rounded">
                    <label class="block text-gray-700 font-bold mb-2 text-lg">カテゴリー</label>
                        <div class="text-2xl font-semibold text-green-800 p-4 rounded">
                            <%= t("categories.#{@item.category}") %>
                        </div>
                    </div>
                </div>

                <div class="mb-4">
                    <div class="bg-gray-100 p-4 rounded">
                    <label class="block text-gray-700 font-bold mb-2 text-lg">商品名</label>
                        <div class="text-2xl font-semibold text-green-800 p-4 rounded">
                            <%= @item.name %>
                        </div>
                    </div>
                </div>

                <div class="mb-4">
                    <div class="bg-gray-100 p-4 rounded">
                    <label class="block text-gray-700 font-bold mb-2 text-lg">内包量</label>
                        <div class="text-2xl font-semibold text-green-800 p-4 rounded">
                            <%= @item.volume %>
                        </div>
                        <span data-items-target="unit" id="unit-span"></span>
                    </div>
                </div>

                <div class="mb-4">
                    <div class="bg-gray-100 p-4 rounded">
                    <label class="block text-gray-700 font-bold mb-2 text-lg">１週間の使用回数</label>
                        <div class="text-2xl font-semibold text-green-800 p-4 rounded">
                            <%= @item.used_count_per_weekly %> 回 / 週
                        </div>
                    </div>
                </div>

                <div class="mb-4">
                    <div class="bg-gray-100 p-4 rounded">
                    <label class="block text-gray-700 font-bold mb-2 text-lg">メモ内容</label>
                        <div class="text-xl font-semibold text-green-800 p-4 rounded">
                            <% if @item.memo.present? %>
                                <%= @item.memo %>
                            <% else %>
                                未登録
                            <% end %>
                        </div>
                    </div>
                </div>

                <div class="mb-4">
                    <div class="bg-gray-100 p-4 rounded">
                    <label class="block text-gray-700 font-bold text-lg">次回の通知日</label>
                    <div id=<%= "notification_mobile_#{@notification.id}" %> class="text-2xl font-semibold text-green-800 p-4 rounded">
                            <%= @notification.next_notification_day %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>